language: r
cache: packages
before_install:
  - cd First_project
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("Euclidean")'
script:
  - Rscript -e 'devtools::check("Euclidean")'